# Data for options dialog

LANG_VOICE_HINT = {
            "fr": ["Français (France) — français (France)"],
            "en": [
                "Anglais (États-Unis) — English (United States)",
                "Anglais (Royaume-Uni) — English (United Kingdom)",
                "Anglais (Canada) — English (Canada)",
                "Anglais (Australie) — English (Australia)",
            ],
            "de": [
                "Allemand (Allemagne) — Deutsch (Deutschland)",
                "Allemand (Autriche) — Deutsch (Österreich)",
                "Allemand (Suisse) — Deutsch (Schweiz)",
            ],
            "es": [
                "Espagnol (Espagne) — Español (España)",
                "Espagnol (Mexique) — Español (México)",
                "Espagnol (États-Unis) — Español (Estados Unidos)",
            ],
            "it": ["Italien (Italie) — Italiano (Italia)"],
            "pt": [
                "Portugais (Brésil) — Português (Brasil)",
                "Portugais (Portugal) — Português (Portugal)",
            ],
            "nl": ["Néerlandais (Pays-Bas) — Nederlands (Nederland)"],
            "ru": ["Russe (Russie) — Русский (Россия)"],
            "ja": ["Japonais (Japon) — 日本語 (日本)"],
            "zh": [
                "Chinois (simplifié, Chine) — 中文 (简体，中国)",
                "Chinois (traditionnel, Taïwan) — 中文 (繁體，台灣)",
            ],
            "ar": [
                "Arabe (Émirats arabes unis) — العربية (الإمارات العربية المتحدة)",
                "Arabe (Bahreïn) — العربية (البحرين)",
                "Arabe (Algérie) — العربية (الجزائر)",
                "Arabe (Égypte) — العربية (مصر)",
                "Arabe (Irak) — العربية (العراق)",
                "Arabe (Jordanie) — العربية (الأردن)",
                "Arabe (Koweït) — العربية (الكويت)",
                "Arabe (Liban) — العربية (لبنان)",
                "Arabe (Libye) — العربية (ليبيا)",
                "Arabe (Maroc) — العربية (المغرب)",
                "Arabe (Oman) — العربية (عُمان)",
                "Arabe (Qatar) — العربية (قطر)",
                "Arabe (Arabie saoudite) — العربية (السعودية)",
                "Arabe (Syrie) — العربية (سوريا)",
                "Arabe (Tunisie) — العربية (تونس)",
                "Arabe (Yémen) — العربية (اليمن)",
            ],
        }

TARGET_LANG_LABELS = [
            ("Français", "fr"),
            ("English", "en"),
            ("Deutsch", "de"),
            ("Español", "es"),
            ("Italiano", "it"),
            ("Português", "pt"),
            ("Nederlands", "nl"),
            ("Русский", "ru"),
            ("日本語", "ja"),
            ("中文", "zh"),
            ("العربية", "ar"),
        ]
UI_LANG_LABELS = [
    ("Français", "fr"),
    ("English", "en"),
    ("Deutsch", "de"),
    ("Español", "es"),
    ("Italiano", "it"),
    ("Português", "pt"),
    ("Nederlands", "nl"),
    ("Русский", "ru"),
    ("日本語", "ja"),
    ("中文", "zh"),
    ("العربية", "ar"),
]

TARGET_LANG_DISPLAY = {
    "fr": {
        "fr": "Francais",
        "en": "Anglais",
        "de": "Allemand",
        "es": "Espagnol",
        "it": "Italien",
        "pt": "Portugais",
        "nl": "Neerlandais",
        "ru": "Russe",
        "ja": "Japonais",
        "zh": "Chinois",
        "ar": "Arabe",
    },
    "en": {
        "fr": "French",
        "en": "English",
        "de": "German",
        "es": "Spanish",
        "it": "Italian",
        "pt": "Portuguese",
        "nl": "Dutch",
        "ru": "Russian",
        "ja": "Japanese",
        "zh": "Chinese",
        "ar": "Arabic",
    },
    "de": {
        "fr": "Franzosisch",
        "en": "Englisch",
        "de": "Deutsch",
        "es": "Spanisch",
        "it": "Italienisch",
        "pt": "Portugiesisch",
        "nl": "Niederlandisch",
        "ru": "Russisch",
        "ja": "Japanisch",
        "zh": "Chinesisch",
        "ar": "Arabisch",
    },
    "es": {
        "fr": "Frances",
        "en": "Ingles",
        "de": "Aleman",
        "es": "Espanol",
        "it": "Italiano",
        "pt": "Portugues",
        "nl": "Neerlandes",
        "ru": "Ruso",
        "ja": "Japones",
        "zh": "Chino",
        "ar": "Arabe",
    },
    "it": {
        "fr": "Francese",
        "en": "Inglese",
        "de": "Tedesco",
        "es": "Spagnolo",
        "it": "Italiano",
        "pt": "Portoghese",
        "nl": "Olandese",
        "ru": "Russo",
        "ja": "Giapponese",
        "zh": "Cinese",
        "ar": "Arabo",
    },
    "pt": {
        "fr": "Frances",
        "en": "Ingles",
        "de": "Alemao",
        "es": "Espanhol",
        "it": "Italiano",
        "pt": "Portugues",
        "nl": "Neerlandes",
        "ru": "Russo",
        "ja": "Japones",
        "zh": "Chines",
        "ar": "Arabe",
    },
    "nl": {
        "fr": "Frans",
        "en": "Engels",
        "de": "Duits",
        "es": "Spaans",
        "it": "Italiaans",
        "pt": "Portugees",
        "nl": "Nederlands",
        "ru": "Russisch",
        "ja": "Japans",
        "zh": "Chinees",
        "ar": "Arabisch",
    },
    "ru": {
        "fr": "Francuzskiy",
        "en": "Angliyskiy",
        "de": "Nemetskiy",
        "es": "Ispanskiy",
        "it": "Italyanskiy",
        "pt": "Portugalskiy",
        "nl": "Niderlandskiy",
        "ru": "Russkiy",
        "ja": "Yaponskiy",
        "zh": "Kitayskiy",
        "ar": "Arabskiy",
    },
    "ja": {
        "fr": "Furansu-go",
        "en": "Eigo",
        "de": "Doitsu-go",
        "es": "Supein-go",
        "it": "Itaria-go",
        "pt": "Porutogaru-go",
        "nl": "Oranda-go",
        "ru": "Roshia-go",
        "ja": "Nihongo",
        "zh": "Chugoku-go",
        "ar": "Arabia-go",
    },
    "zh": {
        "fr": "Fayu",
        "en": "Yingyu",
        "de": "Deyu",
        "es": "Xibanya yu",
        "it": "Yidali yu",
        "pt": "Putao ya yu",
        "nl": "Helan yu",
        "ru": "Eyu",
        "ja": "Riyu",
        "zh": "Hanyu",
        "ar": "Alabo yu",
    },
    "ar": {
        "fr": "Faransi",
        "en": "Injilizi",
        "de": "Almani",
        "es": "Isbani",
        "it": "Itali",
        "pt": "Burtughali",
        "nl": "Hulandi",
        "ru": "Rusi",
        "ja": "Yabani",
        "zh": "Sini",
        "ar": "Arabi",
    },
}

TARGET_LANG_PREFIX = {
    "fr": "Langue cible : ",
    "en": "Target language: ",
    "de": "Zielsprache: ",
    "es": "Idioma de destino: ",
    "it": "Lingua di destinazione: ",
    "pt": "Idioma alvo: ",
    "nl": "Doeltaal: ",
    "ru": "Tselevoj yazyk: ",
    "ja": "Taisyo gengo: ",
    "zh": "Mubiao yuyan: ",
    "ar": "Allugha alhadafa: ",
}

def get_target_lang_label(ui_lang: str, target_lang: str) -> str:
    base = (ui_lang or "fr").split("-")[0]
    code = (target_lang or "").lower()
    names = TARGET_LANG_DISPLAY.get(base, {})
    if code in names:
        return names[code]
    label_map = {code.lower(): label for label, code in TARGET_LANG_LABELS}
    return label_map.get(code, target_lang or "")

def get_target_lang_label_text(ui_lang: str, target_lang: str) -> str:
    base = (ui_lang or "fr").split("-")[0]
    prefix = TARGET_LANG_PREFIX.get(base, TARGET_LANG_PREFIX["fr"])
    return prefix + get_target_lang_label(ui_lang, target_lang)


TARGET_LANG_PHRASES = {
            "fr": "la langue cible est le français",
            "en": "the target language is English",
            "de": "die Zielsprache ist Deutsch",
            "es": "el idioma de destino es español",
            "it": "la lingua di destinazione è l'italiano",
            "pt": "o idioma de destino é o português",
            "nl": "de doeltaal is Nederlands",
            "ru": "целевой язык — русский",
            "ja": "ターゲット言語は日本語です",
            "zh": "目标语言是中文",
            "ar": "اللغة المستهدفة هي العربية",
        }

UI_TRANSLATIONS = {
    "fr": {
        "grp_tts": "TTS",
        "grp_lang": "Langue & Traduction",
        "grp_beh": "Comportement",
        "grp_general": "Général",
        "ui_lang": "Langue interface :",
        "app_paused": "Mettre le service en pause",
        "tts_mute": "Muet (coupe la lecture)",
        "voice": "Voix :",
        "rate": "Vitesse :",
        "volume": "Volume :",
        "test": "Tester la voix",
        "translate": "Traduire si nécessaire (googletrans)",
        "target": "Langue cible :",
        "auto_read": "Lecture automatique des nouvelles réponses",
        "bar_top": "Afficher la barre flottante",
        "bar_start": "Afficher la barre flottante au demarrage",
        "show_text": "Afficher la fenetre de traduction",
        "ok": "OK",
        "cancel": "Annuler",
    },
    "en": {
        "grp_tts": "TTS",
        "grp_lang": "Language & Translation",
        "grp_beh": "Behavior",
        "grp_general": "General",
        "ui_lang": "Interface language:",
        "app_paused": "Pause the service",
        "tts_mute": "Mute (stop playback)",
        "voice": "Voice:",
        "rate": "Speed:",
        "volume": "Volume:",
        "test": "Test voice",
        "translate": "Translate if needed (googletrans)",
        "target": "Target language:",
        "auto_read": "Auto-read new responses",
        "bar_top": "Show the floating bar",
        "bar_start": "Show the floating bar on startup",
        "show_text": "Show the translation window",
        "ok": "OK",
        "cancel": "Cancel",
    },
    "de": {
        "grp_tts": "TTS",
        "grp_lang": "Sprache & Übersetzung",
        "grp_beh": "Verhalten",
        "grp_general": "Allgemein",
        "ui_lang": "Sprache der Oberfläche:",
        "app_paused": "Dienst pausieren",
        "tts_mute": "Stumm (Wiedergabe stoppen)",
        "voice": "Stimme:",
        "rate": "Geschwindigkeit:",
        "volume": "Lautstärke:",
        "test": "Stimme testen",
        "translate": "Übersetzen wenn nötig (googletrans)",
        "target": "Zielsprache:",
        "auto_read": "Neue Antworten automatisch lesen",
        "bar_top": "Schwebebalken anzeigen",
        "bar_start": "Schwebebalken beim Start anzeigen",
        "show_text": "Übersetzungsfenster anzeigen",
        "ok": "OK",
        "cancel": "Abbrechen",
    },
    "es": {
        "grp_tts": "TTS",
        "grp_lang": "Idioma y traducción",
        "grp_beh": "Comportamiento",
        "grp_general": "General",
        "ui_lang": "Idioma de la interfaz:",
        "app_paused": "Pausar el servicio",
        "tts_mute": "Silencio (detener reproducción)",
        "voice": "Voz:",
        "rate": "Velocidad:",
        "volume": "Volumen:",
        "test": "Probar voz",
        "translate": "Traducir si es necesario (googletrans)",
        "target": "Idioma de destino:",
        "auto_read": "Lectura automática de nuevas respuestas",
        "bar_top": "Mostrar la barra flotante",
        "bar_start": "Mostrar la barra flotante al iniciar",
        "show_text": "Mostrar la ventana de traducción",
        "ok": "OK",
        "cancel": "Cancelar",
    },
    "it": {
        "grp_tts": "TTS",
        "grp_lang": "Lingua e traduzione",
        "grp_beh": "Comportamento",
        "grp_general": "Generale",
        "ui_lang": "Lingua dell'interfaccia:",
        "app_paused": "Metti in pausa il servizio",
        "tts_mute": "Muto (ferma la riproduzione)",
        "voice": "Voce:",
        "rate": "Velocità:",
        "volume": "Volume:",
        "test": "Prova voce",
        "translate": "Traduci se necessario (googletrans)",
        "target": "Lingua di destinazione:",
        "auto_read": "Lettura automatica delle nuove risposte",
        "bar_top": "Mostra la barra flottante",
        "bar_start": "Mostra la barra flottante all'avvio",
        "show_text": "Mostra la finestra di traduzione",
        "ok": "OK",
        "cancel": "Annulla",
    },
    "pt": {
        "grp_tts": "TTS",
        "grp_lang": "Idioma e tradução",
        "grp_beh": "Comportamento",
        "grp_general": "Geral",
        "ui_lang": "Idioma da interface:",
        "app_paused": "Pausar o serviço",
        "tts_mute": "Mudo (parar reprodução)",
        "voice": "Voz:",
        "rate": "Velocidade:",
        "volume": "Volume:",
        "test": "Testar voz",
        "translate": "Traduzir se necessário (googletrans)",
        "target": "Idioma alvo:",
        "auto_read": "Leitura automática de novas respostas",
        "bar_top": "Mostrar a barra flutuante",
        "bar_start": "Mostrar a barra flutuante ao iniciar",
        "show_text": "Mostrar a janela de tradução",
        "ok": "OK",
        "cancel": "Cancelar",
    },
    "nl": {
        "grp_tts": "TTS",
        "grp_lang": "Taal en vertaling",
        "grp_beh": "Gedrag",
        "grp_general": "Algemeen",
        "ui_lang": "Interfacetaal:",
        "app_paused": "Service pauzeren",
        "tts_mute": "Dempen (afspelen stoppen)",
        "voice": "Stem:",
        "rate": "Snelheid:",
        "volume": "Volume:",
        "test": "Stem testen",
        "translate": "Vertalen indien nodig (googletrans)",
        "target": "Doeltaal:",
        "auto_read": "Nieuwe antwoorden automatisch lezen",
        "bar_top": "Zwevende balk tonen",
        "bar_start": "Zwevende balk bij opstarten tonen",
        "show_text": "Vertaalvenster tonen",
        "ok": "OK",
        "cancel": "Annuleren",
    },
    "ru": {
        "grp_tts": "TTS",
        "grp_lang": "Язык и перевод",
        "grp_beh": "Поведение",
        "grp_general": "Общие",
        "ui_lang": "Язык интерфейса:",
        "app_paused": "Пауза службы",
        "tts_mute": "Без звука (остановить воспроизведение)",
        "voice": "Голос:",
        "rate": "Скорость:",
        "volume": "Громкость:",
        "test": "Проверить голос",
        "translate": "Переводить при необходимости (googletrans)",
        "target": "Целевой язык:",
        "auto_read": "Авточтение новых ответов",
        "bar_top": "Показывать плавающую панель",
        "bar_start": "Показывать плавающую панель при запуске",
        "show_text": "Показывать окно перевода",
        "ok": "OK",
        "cancel": "Отмена",
    },
    "ja": {
        "grp_tts": "TTS",
        "grp_lang": "言語と翻訳",
        "grp_beh": "動作",
        "grp_general": "一般",
        "ui_lang": "インターフェース言語:",
        "app_paused": "サービスを一時停止",
        "tts_mute": "ミュート（再生停止）",
        "voice": "音声:",
        "rate": "速度:",
        "volume": "音量:",
        "test": "音声テスト",
        "translate": "必要に応じて翻訳 (googletrans)",
        "target": "対象言語:",
        "auto_read": "新しい返信を自動読み上げ",
        "bar_top": "フローティングバーを表示",
        "bar_start": "起動時にフローティングバーを表示",
        "show_text": "翻訳ウィンドウを表示",
        "ok": "OK",
        "cancel": "キャンセル",
    },
    "zh": {
        "grp_tts": "TTS",
        "grp_lang": "语言与翻译",
        "grp_beh": "行为",
        "grp_general": "常规",
        "ui_lang": "界面语言:",
        "app_paused": "暂停服务",
        "tts_mute": "静音（停止播放）",
        "voice": "声音:",
        "rate": "速度:",
        "volume": "音量:",
        "test": "测试声音",
        "translate": "需要时翻译 (googletrans)",
        "target": "目标语言:",
        "auto_read": "自动朗读新回复",
        "bar_top": "显示浮动栏",
        "bar_start": "启动时显示浮动栏",
        "show_text": "显示翻译窗口",
        "ok": "OK",
        "cancel": "取消",
    },
    "ar": {
        "grp_tts": "TTS",
        "grp_lang": "اللغة والترجمة",
        "grp_beh": "السلوك",
        "grp_general": "عام",
        "ui_lang": "لغة الواجهة:",
        "app_paused": "إيقاف الخدمة مؤقتًا",
        "tts_mute": "كتم (إيقاف التشغيل)",
        "voice": "الصوت:",
        "rate": "السرعة:",
        "volume": "الصوت:",
        "test": "اختبار الصوت",
        "translate": "ترجمة عند الحاجة (googletrans)",
        "target": "اللغة المستهدفة:",
        "auto_read": "قراءة تلقائية للردود الجديدة",
        "bar_top": "إظهار الشريط العائم",
        "bar_start": "إظهار الشريط العائم عند البدء",
        "show_text": "إظهار نافذة الترجمة",
        "ok": "موافق",
        "cancel": "إلغاء",
    },
}

def build_announce_phrases(voice_label, rate_pct, volume, enabled, muted, paused, target_lang_phrase):
    return {
    "fr": {
        "voice": f"la voix est maintenant {voice_label}",
        "rate": f"la vitesse de la voix est réglée sur {rate_pct} pour cent",
        "volume": f"le volume est réglé sur {volume} pour cent",
        "app_paused": "le service est en pause" if paused else "le service est actif",
        "tts_mute": "le tts est en mode muet" if muted else "le tts n'est plus en mode muet",
        "translate": "la traduction est activée" if enabled else "la traduction est désactivée",
        "auto_read": "la lecture automatique est activée" if enabled else "la lecture automatique est désactivée",
        "bar_top": "la barre flottante est affichée" if enabled else "la barre flottante est masquée",
        "bar_start": "la barre flottante s'affichera au démarrage" if enabled else "la barre flottante ne s'affichera pas au démarrage",
        "show_text": "l'affichage du texte est activé" if enabled else "l'affichage du texte est désactivé",
        "target_lang": target_lang_phrase,
    },
    "en": {
        "voice": f"the voice is now {voice_label}",
        "rate": f"the voice speed is set to {rate_pct} percent",
        "volume": f"the volume is set to {volume} percent",
        "app_paused": "the service is paused" if paused else "the service is active",
        "tts_mute": "tts is muted" if muted else "tts is unmuted",
        "translate": "translation is enabled" if enabled else "translation is disabled",
        "auto_read": "auto read is enabled" if enabled else "auto read is disabled",
        "bar_top": "floating bar is shown" if enabled else "floating bar is hidden",
        "bar_start": "floating bar will show on startup" if enabled else "floating bar will not show on startup",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "de": {
        "voice": f"die stimme ist jetzt {voice_label}",
        "rate": f"die sprachgeschwindigkeit ist auf {rate_pct} prozent eingestellt",
        "volume": f"die lautstärke ist auf {volume} prozent eingestellt",
        "app_paused": "der dienst ist pausiert" if paused else "der dienst ist aktiv",
        "tts_mute": "tts ist stummgeschaltet" if muted else "tts ist nicht mehr stummgeschaltet",
        "translate": "übersetzung ist aktiviert" if enabled else "übersetzung ist deaktiviert",
        "auto_read": "automatisches vorlesen ist aktiviert" if enabled else "automatisches vorlesen ist deaktiviert",
        "bar_top": "schwebebalken wird angezeigt" if enabled else "schwebebalken ist ausgeblendet",
        "bar_start": "schwebebalken wird beim start angezeigt" if enabled else "schwebebalken wird beim start nicht angezeigt",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "es": {
        "voice": f"la voz ahora es {voice_label}",
        "rate": f"la velocidad de la voz está en {rate_pct} por ciento",
        "volume": f"el volumen está en {volume} por ciento",
        "app_paused": "el servicio está en pausa" if paused else "el servicio está activo",
        "tts_mute": "tts está silenciado" if muted else "tts ya no está silenciado",
        "translate": "la traducción está activada" if enabled else "la traducción está desactivada",
        "auto_read": "la lectura automática está activada" if enabled else "la lectura automática está desactivada",
        "bar_top": "la barra flotante está visible" if enabled else "la barra flotante está oculta",
        "bar_start": "la barra flotante se mostrará al inicio" if enabled else "la barra flotante no se mostrará al inicio",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "it": {
        "voice": f"la voce è ora {voice_label}",
        "rate": f"la velocità della voce è impostata su {rate_pct} per cento",
        "volume": f"il volume è impostato su {volume} per cento",
        "app_paused": "il servizio è in pausa" if paused else "il servizio è attivo",
        "tts_mute": "tts è disattivato audio" if muted else "tts non è più disattivato audio",
        "translate": "la traduzione è attivata" if enabled else "la traduzione è disattivata",
        "auto_read": "la lettura automatica è attivata" if enabled else "la lettura automatica è disattivata",
        "bar_top": "la barra flottante è visibile" if enabled else "la barra flottante è nascosta",
        "bar_start": "la barra flottante sarà mostrata all'avvio" if enabled else "la barra flottante non sarà mostrata all'avvio",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "pt": {
        "voice": f"a voz agora é {voice_label}",
        "rate": f"a velocidade da voz está em {rate_pct} por cento",
        "volume": f"o volume está em {volume} por cento",
        "app_paused": "o serviço está em pausa" if paused else "o serviço está ativo",
        "tts_mute": "tts está mudo" if muted else "tts não está mais mudo",
        "translate": "a tradução está ativada" if enabled else "a tradução está desativada",
        "auto_read": "a leitura automática está ativada" if enabled else "a leitura automática está desativada",
        "bar_top": "a barra flutuante está visível" if enabled else "a barra flutuante está oculta",
        "bar_start": "a barra flutuante será mostrada na inicialização" if enabled else "a barra flutuante não será mostrada na inicialização",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "nl": {
        "voice": f"de stem is nu {voice_label}",
        "rate": f"de stemsnelheid staat op {rate_pct} procent",
        "volume": f"het volume staat op {volume} procent",
        "app_paused": "de service is gepauzeerd" if paused else "de service is actief",
        "tts_mute": "tts is gedempt" if muted else "tts is niet meer gedempt",
        "translate": "vertaling is ingeschakeld" if enabled else "vertaling is uitgeschakeld",
        "auto_read": "automatisch lezen is ingeschakeld" if enabled else "automatisch lezen is uitgeschakeld",
        "bar_top": "zwevende balk is zichtbaar" if enabled else "zwevende balk is verborgen",
        "bar_start": "zwevende balk wordt bij start getoond" if enabled else "zwevende balk wordt bij start niet getoond",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "ru": {
        "voice": f"голос теперь {voice_label}",
        "rate": f"скорость речи установлена на {rate_pct} процентов",
        "volume": f"громкость установлена на {volume} процентов",
        "app_paused": "служба на паузе" if paused else "служба активна",
        "tts_mute": "tts в режиме без звука" if muted else "tts без звука отключен",
        "translate": "перевод включен" if enabled else "перевод отключен",
        "auto_read": "авточтение включено" if enabled else "авточтение отключено",
        "bar_top": "плавающая панель показана" if enabled else "плавающая панель скрыта",
        "bar_start": "плавающая панель будет показана при запуске" if enabled else "плавающая панель не будет показана при запуске",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "ja": {
        "voice": f"音声は現在 {voice_label} です",
        "rate": f"音声の速度は {rate_pct} パーセントに設定されています",
        "volume": f"音量は {volume} パーセントに設定されています",
        "app_paused": "サービスは一時停止中です" if paused else "サービスはアクティブです",
        "tts_mute": "tts はミュートです" if muted else "tts はミュート解除されています",
        "translate": "翻訳が有効です" if enabled else "翻訳が無効です",
        "auto_read": "自動読み上げが有効です" if enabled else "自動読み上げが無効です",
        "bar_top": "フローティングバーが表示されています" if enabled else "フローティングバーは非表示です",
        "bar_start": "フローティングバーは起動時に表示されます" if enabled else "フローティングバーは起動時に表示されません",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "zh": {
        "voice": f"当前语音为 {voice_label}",
        "rate": f"语速设置为 {rate_pct} 百分比",
        "volume": f"音量设置为 {volume} 百分比",
        "app_paused": "服务已暂停" if paused else "服务已激活",
        "tts_mute": "tts 已静音" if muted else "tts 已取消静音",
        "translate": "翻译已启用" if enabled else "翻译已禁用",
        "auto_read": "自动朗读已启用" if enabled else "自动朗读已禁用",
        "bar_top": "浮动栏已显示" if enabled else "浮动栏已隐藏",
        "bar_start": "浮动栏将在启动时显示" if enabled else "浮动栏不会在启动时显示",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
    "ar": {
        "voice": f"الصوت الآن {voice_label}",
        "rate": f"سرعة الصوت مضبوطة على {rate_pct} بالمائة",
        "volume": f"مستوى الصوت مضبوط على {volume} بالمائة",
        "app_paused": "الخدمة متوقفة مؤقتًا" if paused else "الخدمة نشطة",
        "tts_mute": "tts في وضع كتم الصوت" if muted else "تم إلغاء كتم tts",
        "translate": "تم تفعيل الترجمة" if enabled else "تم إيقاف الترجمة",
        "auto_read": "تم تفعيل القراءة التلقائية" if enabled else "تم إيقاف القراءة التلقائية",
        "bar_top": "الشريط العائم ظاهر" if enabled else "الشريط العائم مخفي",
        "bar_start": "سيظهر الشريط العائم عند البدء" if enabled else "لن يظهر الشريط العائم عند البدء",
        "show_text": "translation window is shown" if enabled else "translation window is hidden",
        "target_lang": target_lang_phrase,
    },
}
